# NCUACG/NCUACG/settings.py
"""
Django settings for NCUACG project.

Generated by 'django-admin startproject' using Django 5.2.
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)2vb3+ck^1)b#twv#3p9gb7uei=bhh1srkuec8$#2*82#mn78z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 更友善的預設：本機開發允許 localhost 與 127.0.0.1；也可用環境變數覆蓋
ALLOWED_HOSTS = (
    os.getenv("ALLOWED_HOSTS").split(",")
    if os.getenv("ALLOWED_HOSTS")
    else ["localhost", "127.0.0.1"]
)

# Application definition
INSTALLED_APPS = [
    # CORS 必須在最前的 middleware 生效，這裡是 app 註冊
    'corsheaders',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',

    # 你的 app（改為啟用）
    'accounts',
    'captcha',
    'assistant',
    'club',
    'event',
    'home',
]

MIDDLEWARE = [
    # ★ CORS 中介層建議放在最前，先處理預檢請求（OPTIONS）
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'NCUACG.urls'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # 讓 API 輸出的時間統一用 ISO8601（含時區偏移）
    'DATETIME_FORMAT': "%Y-%m-%dT%H:%M:%S%z",
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NCUACG.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'

# ★ 改成台灣時區；仍保留 USE_TZ=True（DB 存 UTC，程式用本地時區進行運算/顯示）
TIME_ZONE = 'Asia/Taipei'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ─────────────────────────────────────────────────────────────────────────────
# 站內慣例：統一使用尾斜線，避免 307 導致 POST 資料丟失
APPEND_SLASH = True

# ─────────────────────────────────────────────────────────────────────────────
# CORS 設定（只開放必要 API 路徑）
_FRONTEND_ORIGIN = os.getenv("FRONTEND_ORIGIN", "").strip()
CORS_ALLOWED_ORIGINS = [o for o in [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    _FRONTEND_ORIGIN,
] if o]

# 僅套用到 /api/assistant/* 與 /api/event/* 路徑，縮小暴露面
CORS_URLS_REGEX = r"^/api/(assistant|event)/.*$"

# 若需要帶 Cookie / Session
CORS_ALLOW_CREDENTIALS = True

# 使用 Session/CSRF 時請同步信任前端網域（JWT 可不需）
CSRF_TRUSTED_ORIGINS = [
    o.replace("http://", "http://").replace("https://", "https://") for o in CORS_ALLOWED_ORIGINS
]

# ─────────────────────────────────────────────────────────────────────────────
# 事件查詢預設視窗（天數）：event/views.py 可以讀此設定做預設過濾（未來 N 天）
DEFAULT_EVENT_WINDOW_DAYS = int(os.getenv("DEFAULT_EVENT_WINDOW_DAYS", "30"))
