# NCUACG/NCUACG/settings.py
"""
Django settings for NCUACG project.

Generated by 'django-admin startproject' using Django 5.2.
"""
from corsheaders.defaults import default_headers
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)2vb3+ck^1)b#twv#3p9gb7uei=bhh1srkuec8$#2*82#mn78z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 更友善的預設：本機開發允許 localhost 與 127.0.0.1；也可用環境變數覆蓋
ALLOWED_HOSTS = (
    os.getenv("ALLOWED_HOSTS").split(",")
    if os.getenv("ALLOWED_HOSTS")
    else ["localhost", "127.0.0.1"]
)

# Application definition
INSTALLED_APPS = [
    # CORS 需在 middleware 生效，這裡是 app 註冊
    'corsheaders',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',

    # 你的 app
    'accounts',
    'captcha',
    'assistant',
    'club',
    'event',
    'home',
]

MIDDLEWARE = [
    # ★ CORS 中介層建議放在最前，先處理預檢請求（OPTIONS）
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'NCUACG.urls'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # 讓 API 輸出的時間統一用 ISO8601（含時區偏移）
    'DATETIME_FORMAT': "%Y-%m-%dT%H:%M:%S%z",
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,

    # 🔑 關鍵設定：告訴 SimpleJWT 用 payload 中的 'id' 欄位
    'USER_ID_FIELD': 'id',      # Django User model 的 PK 欄位名
    'USER_ID_CLAIM': 'id',      # JWT payload 中的欄位名

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NCUACG.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Captcha 設定（前端分支帶來的配置）
CAPTCHA_CHALLENGE_FUNCT = 'accounts.captcha_config.alnum_case_sensitive'
CAPTCHA_IMAGE_SIZE = (200, 80)    # 調整圖片大小，越大越清晰
CAPTCHA_FONT_SIZE = 48            # 字體大小
CAPTCHA_FOREGROUND_COLOR = '#000000'  # 字體顏色（黑色）

# Email 驗證信寄發（開發用 console backend；上線請改成 SMTP）
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # 正式請用這個
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # 測試用
# EMAIL_HOST = 'smtp.example.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.getenv("verify_email")
# EMAIL_HOST_PASSWORD = os.getenv("verify_email_password")
DEFAULT_FROM_EMAIL = os.getenv("verify_email")

# Internationalization
LANGUAGE_CODE = 'en-us'

# ★ 改成台灣時區；仍保留 USE_TZ=True（DB 存 UTC，程式用本地時區進行運算/顯示）
TIME_ZONE = 'Asia/Taipei'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging（保留前端分支設定，方便本機除錯）
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    'loggers': {
        '': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# ─────────────────────────────────────────────────────────────────────────────
# 站內慣例：統一使用尾斜線，避免 307 導致 POST 資料丟失
APPEND_SLASH = True

# ─────────────────────────────────────────────────────────────────────────────
# CORS 設定（整合兩分支：白名單 + 只開放必要 API 路徑）
_FRONTEND_ORIGIN = os.getenv("FRONTEND_ORIGIN", "").strip()
CORS_ALLOWED_ORIGINS = [o for o in [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    _FRONTEND_ORIGIN,
] if o]

# 只對 /api/assistant/* 與 /api/event/* 套用 CORS，縮小暴露面
CORS_URLS_REGEX = r"^/api/.*$"

# 若前端需要帶 Cookie/Session
CORS_ALLOW_CREDENTIALS = True

# 允許的自訂標頭（綜合前端分支）
CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-csrftoken",   # 你需要額外允許的
]

# 使用 Session/CSRF 時請同步信任前端網域（JWT 可不需）
CSRF_TRUSTED_ORIGINS = [
    o.replace("http://", "http://").replace("https://", "https://") for o in CORS_ALLOWED_ORIGINS
]

# ─────────────────────────────────────────────────────────────────────────────
# 事件查詢預設視窗（天數）：event/views.py 可以讀此設定做預設過濾（未來 N 天）
DEFAULT_EVENT_WINDOW_DAYS = int(os.getenv("DEFAULT_EVENT_WINDOW_DAYS", "30"))
