# Generated by Django 5.2.5 on 2025-09-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_admin_user_is_super_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='last_login',
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
