# Generated by Django 5.2.5 on 2025-09-17 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_credential_last_login_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='username',
        ),
    ]
